

# This file was *autogenerated* from the file bold.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_0 = Integer(0); _sage_const_500 = Integer(500); _sage_const_400 = Integer(400)# b = initial bankroll
# w = win probability
# r = net return fraction on bet if we win
# p = probability of reaching 1 before busting
# c = current state probability

b = _sage_const_1 /_sage_const_2 
w = _sage_const_1 /_sage_const_2 
r = _sage_const_1 /_sage_const_2 
p = _sage_const_0 
c = _sage_const_1 

for i in range(_sage_const_0 ,_sage_const_500 ):
    
    if (_sage_const_1 +r)*b < _sage_const_1 :
        # Bet all
        c = w*c
        b = (_sage_const_1 +r)*b
    else:
        # Bet x such that x*r + b = 1
        # x = (1-b)/r
        # Win
        p += w*c
        # Lose
        b -= (_sage_const_1 -b)/r
        c = (_sage_const_1 -w)*c
    # Finished on a stopper
    if (b==_sage_const_0 ):
        break

print(p)
print(p.n(prec=_sage_const_400 ))

