

# This file was *autogenerated* from the file random_fibonacci.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1p0 = RealNumber('1.0'); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_1000000 = Integer(1000000); _sage_const_101 = Integer(101); _sage_const_48 = Integer(48)
a = _sage_const_1p0 
b = _sage_const_1p0 

n = _sage_const_1 
for i in range(_sage_const_2 ,_sage_const_1000000 ):
    c = (_sage_const_2 -_sage_const_1 /n)*b - (_sage_const_1 -_sage_const_2 /n)*a
    a = b
    b = c
    n += _sage_const_1 

n += _sage_const_1 

print("Actual, n = {}, value = {}".format(n,b.n()))

x = _sage_const_1 /sqrt(e*pi)*( exp(_sage_const_2 *sqrt(n))/(sqrt(n)*sqrt(sqrt(n))) * (_sage_const_1 -_sage_const_101 /_sage_const_48 *_sage_const_1 /sqrt(n)))
print("Wong-Li asymptotics, value = {}".format(x.n()))

print("Ratio = {}".format((b/x).n()))

